version: '2'

services:
  ftpd_server:
   image: stilliard/pure-ftpd:hardened
   container_name: pure-ftpd
   ports:
    -"21:21"
    -"30000-30009:30000-30009"
  volumes:
    -"./data:/home/052"
  environment:
    PUBLICHOST: "Localhost"
    FTP_USER_NAME: 052
    FTP_USER_PASS: 1234
    FTP_USER_HOME: /home/052
  restart: always      